// Generated by CoffeeScript 1.8.0
(function() {
  var Repositoty;

  module.exports = Repositoty = {};

  Repositoty.Database = (function() {
    function Database(db) {
      this.db = db;
    }

    Database.prototype.getCollection = function(name) {
      throw 'not implemented';
    };

    return Database;

  })();

  Repositoty.Collection = (function() {
    function Collection() {}

    Collection.prototype.find = function() {};

    Collection.prototype.findById = function() {};

    Collection.prototype.save = function() {};

    Collection.prototype.where = function() {};

    Collection.prototype.findOne = function() {};

    Collection.prototype.remove = function() {};

    Collection.prototype.validate = function() {
      return true;
    };

    return Collection;

  })();

}).call(this);
